export const TOGGLE_PLAYER_VISIBILITY: string = "TOGGLE_PLAYER_VISIBILITY";
export const UPDATE_PLAYER_URL: string = "UPDATE_PLAYER_URL";
export const TOGGLE_TIMER_VISIBILITY: string = "TOGGLE_TIMER_VISIBILITY";
